[package]
name = "dijkstra_heap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datastructures = "0.1.1"
regex = "1"
