FROM docker.elastic.co/elasticsearch/elasticsearch:7.13.0

# copy the configuration file into the container
COPY elasticsearch.yml /usr/share/elasticsearch/config

# expose the default Elasticsearch port
EXPOSE 9200

